version: '3.8'

services:
  app:
    image: 'newsportal:latest'
    container_name: app
    ports:
      - "8081:8081"
    links:
      - db
    networks:
      - db

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    build: db
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_portal
    networks:
      - db

volumes:
  db-data:
    driver: local
networks:
  db:
    driver: bridge
